- hosts: ubuntu
  tasks:
  - name: Install apache httpd  (state=present is optional)
    apt:
      name: apache2
      state: present
      update_cache: yes

  - name: Install unzip
    apt:
      name: unzip
      state: present
      update_cache: yes

  - name: Unarchive  a file that needs to be download 
    unarchive:
      src: https://www.free-css.com/assets/files/free-css-templates/download/page292/settle.zip
      dest: /tmp/
      remote_src: yes
      
  - name: Move template files to /var/www/html
    shell: "rm -rf  /var/www/html/*  && mv /tmp/settle-html/* /var/www/html/"